# Generated by Django 5.1.4 on 2026-07-21 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("delivery", "0001_initial"),
        ("market", "0002_cart_marketorder_marketorderitem_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryassignment",
            name="market_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_assignment",
                to="market.marketorder",
            ),
        ),
    ]
