# Generated by Django 5.1.4 on 2026-07-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_email_user_is_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="totp_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
