#!/bin/bash
# ─────────────────────────────────────────────────────────
# Gloss Ecosystem - Blue-Green Production Deployment
# Run: ./scripts/deploy-blue-green.sh [blue|green]
# ─────────────────────────────────────────────────────────

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# Configuration
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="docker-compose.prod.yml"
ENV_FILE=".env.prod"
BLUE_PORT=3000
GREEN_PORT=3001
NGINX_CONF="/etc/nginx/conf.d/upstream.conf"
HEALTH_ENDPOINT="/health"
HEALTH_TIMEOUT=30
HEALTH_INTERVAL=5
ROLLBACK_TIMEOUT=60

# Active color tracking
ACTIVE_COLOR_FILE="/tmp/gloss_active_color"
BACKUP_COLOR_FILE="/tmp/gloss_backup_color"

# ─────────────────────────────────────────────────────────
# Utility Functions
# ─────────────────────────────────────────────────────────

get_active_color() {
    if [[ -f "$ACTIVE_COLOR_FILE" ]]; then
        cat "$ACTIVE_COLOR_FILE"
    else
        echo "blue"  # Default
    fi
}

get_inactive_color() {
    local active=$(get_active_color)
    if [[ "$active" == "blue" ]]; then
        echo "green"
    else
        echo "blue"
    fi
}

get_port_for_color() {
    local color=$1
    if [[ "$color" == "blue" ]]; then
        echo "$BLUE_PORT"
    else
        echo "$GREEN_PORT"
    fi
}

set_active_color() {
    echo "$1" > "$ACTIVE_COLOR_FILE"
    echo "$2" > "$BACKUP_COLOR_FILE"
}

wait_for_health() {
    local color=$1
    local port=$2
    local max_attempts=$((HEALTH_TIMEOUT / HEALTH_INTERVAL))
    local attempt=1
    
    log_info "Waiting for $color (port $port) to become healthy..."
    
    while [[ $attempt -le $max_attempts ]]; do
        if curl -sf "http://localhost:${port}${HEALTH_ENDPOINT}" > /dev/null 2>&1; then
            log_success "$color is healthy!"
            return 0
        fi
        
        log_info "Attempt $attempt/$max_attempts - waiting..."
        sleep "$HEALTH_INTERVAL"
        ((attempt++))
    done
    
    log_error "$color failed health check after ${HEALTH_TIMEOUT}s"
    return 1
}

run_smoke_tests() {
    local color=$1
    local port=$2
    
    log_info "Running smoke tests on $color..."
    
    # Test health endpoint
    if ! curl -sf "http://localhost:${port}/health" | jq -e '.status == "ok"' > /dev/null; then
        log_error "Health check failed"
        return 1
    fi
    
    # Test API version
    if ! curl -sf "http://localhost:${port}/api/v1/version" > /dev/null; then
        log_error "API version endpoint failed"
        return 1
    fi
    
    # Test database connectivity via API
    if ! curl -sf "http://localhost:${port}/health/db" > /dev/null; then
        log_error "Database health check failed"
        return 1
    fi
    
    log_success "Smoke tests passed for $color"
    return 0
}

switch_traffic() {
    local new_color=$1
    local new_port=$(get_port_for_color "$new_color")
    
    log_info "Switching traffic to $new_color (port $new_port)..."
    
    # Update nginx upstream config
    cat > "$NGINX_CONF.tmp" <<EOF
# Gloss Blue-Green Upstream Configuration
# Auto-generated by deploy-blue-green.sh - DO NOT EDIT MANUALLY

upstream gloss_backend {
    least_conn;
    server backend_${new_color}:${new_port} max_fails=3 fail_timeout=30s;
    # Backup server (previous version)
    server backend_$(get_inactive_color):$(get_port_for_color "$(get_inactive_color)") backup;
}

upstream gloss_ws {
    least_conn;
    server backend_${new_color}:${new_port} max_fails=3 fail_timeout=30s;
    server backend_$(get_inactive_color):$(get_port_for_color "$(get_inactive_color)") backup;
}
EOF
    
    # Atomic move and reload nginx
    mv "$NGINX_CONF.tmp" "$NGINX_CONF"
    
    if docker exec gloss-nginx-prod nginx -t; then
        docker exec gloss-nginx-prod nginx -s reload
        log_success "Traffic switched to $new_color"
    else
        log_error "Nginx config test failed, rolling back config"
        mv "$NGINX_CONF.bak" "$NGINX_CONF" 2>/dev/null || true
        return 1
    fi
    
    # Wait for traffic to stabilize
    sleep 5
    
    # Verify new color is receiving traffic
    if curl -sf "http://localhost/health" | jq -e ".color == \"$new_color\"" > /dev/null; then
        log_success "Traffic verified on $new_color"
    else
        log_warn "Could not verify traffic switch, but nginx reloaded successfully"
    fi
}

rollback() {
    log_warn "Initiating rollback..."
    
    local previous_color=$(cat "$BACKUP_COLOR_FILE" 2>/dev/null || echo "blue")
    local previous_port=$(get_port_for_color "$previous_color")
    
    log_info "Rolling back to $previous_color (port $previous_port)"
    
    if switch_traffic "$previous_color"; then
        set_active_color "$previous_color" "$(get_inactive_color)"
        log_success "Rollback completed to $previous_color"
    else
        log_error "Rollback failed! Manual intervention required."
        exit 1
    fi
}

cleanup_old_container() {
    local color=$1
    log_info "Stopping old $color container..."
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" stop "backend_${color}" 2>/dev/null || true
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" rm -f "backend_${color}" 2>/dev/null || true
}

# ─────────────────────────────────────────────────────────
# Main Deployment Functions
# ─────────────────────────────────────────────────────────

deploy_color() {
    local color=$1
    local port=$(get_port_for_color "$color")
    
    log_info "Deploying $color environment (port $port)..."
    
    # Build new image
    log_info "Building $color image..."
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" build "backend_${color}"
    
    # Start new container
    log_info "Starting $color container..."
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d "backend_${color}"
    
    # Wait for health
    if ! wait_for_health "$color" "$port"; then
        log_error "$color deployment failed health check"
        cleanup_old_container "$color"
        return 1
    fi
    
    # Run smoke tests
    if ! run_smoke_tests "$color" "$port"; then
        log_error "$color failed smoke tests"
        cleanup_old_container "$color"
        return 1
    fi
    
    log_success "$color deployed and validated successfully"
    return 0
}

# ─────────────────────────────────────────────────────────
# Main Script
# ─────────────────────────────────────────────────────────

main() {
    cd "$PROJECT_ROOT"
    
    # Parse arguments
    TARGET_COLOR="${1:-}"
    if [[ -z "$TARGET_COLOR" ]]; then
        TARGET_COLOR=$(get_inactive_color)
        log_info "No color specified, deploying to inactive: $TARGET_COLOR"
    fi
    
    if [[ "$TARGET_COLOR" != "blue" && "$TARGET_COLOR" != "green" ]]; then
        log_error "Invalid color: $TARGET_COLOR. Use 'blue' or 'green'"
        exit 1
    fi
    
    ACTIVE_COLOR=$(get_active_color)
    if [[ "$TARGET_COLOR" == "$ACTIVE_COLOR" ]]; then
        log_warn "$TARGET_COLOR is already active. Use 'force' to redeploy."
        if [[ "${2:-}" != "force" ]]; then
            exit 1
        fi
        log_warn "Force redeploying $TARGET_COLOR..."
    fi
    
    log_info "=========================================="
    log_info "Gloss Blue-Green Deployment"
    log_info "Active: $ACTIVE_COLOR | Target: $TARGET_COLOR"
    log_info "=========================================="
    
    # Deploy to target color
    if ! deploy_color "$TARGET_COLOR"; then
        log_error "Deployment failed"
        exit 1
    fi
    
    # Switch traffic
    if ! switch_traffic "$TARGET_COLOR"; then
        log_error "Traffic switch failed, rolling back..."
        rollback
        exit 1
    fi
    
    # Update active color tracking
    set_active_color "$TARGET_COLOR" "$ACTIVE_COLOR"
    
    # Cleanup old container after successful switch
    cleanup_old_container "$ACTIVE_COLOR"
    
    log_success "=========================================="
    log_success "Blue-Green Deployment Complete!"
    log_success "Active: $TARGET_COLOR"
    log_success "Previous: $ACTIVE_COLOR (available for rollback)"
    log_success "=========================================="
}

# Handle signals
trap 'log_error "Deployment interrupted"; exit 1' INT TERM

# Run main
main "$@"