# Generated by Django 5.1.4 on 2026-07-21 15:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_commissionrule_min_order_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.15"),
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
    ]
