# Generated by Django 5.1.4 on 2026-07-21 10:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workforce", "0002_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
