# Generated by Django 5.1.4 on 2026-07-21 11:05

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workforce", "0003_team_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"base_manager_name": "all_tenants"},
        ),
        migrations.AlterModelOptions(
            name="workerinvitecode",
            options={"base_manager_name": "all_tenants"},
        ),
        migrations.AlterModelOptions(
            name="workerprofile",
            options={"base_manager_name": "all_tenants"},
        ),
        migrations.AlterModelManagers(
            name="team",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="workerinvitecode",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="workerprofile",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_tenants", django.db.models.manager.Manager()),
            ],
        ),
    ]
